### ISSUE TITLE
Error in data.frame(seqnames = paste0("chr", gene_info$data$seq_region_name),  :    arguments imply differing number of rows: 1, 0 

### ISSUE THREAD

**Issue by ann081993** [syhwang-snu/ASO_Gen#1]
<pre tabindex="0" class="GD15MCFCEUB" id="rstudio_console_output" style="font-family: &quot;DejaVu Sans Mono&quot;, monospace; font-size: 14.6667px; outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; line-height: 1.25; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 34, 64); text-decoration-style: initial; text-decoration-color: initial;"><span><span class="GD15MCFCKTB ace_keyword" style="color: rgb(255, 157, 0);">seqList &lt;- makeSequenceLists(gene_symbol = "POLR2A")
</span><span class="GD15MCFCEUB" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">[1] "Find Gene Information of POLR2A in human"
[1] "get data for gene ID ENSG00000181222"
[1] "Get Main species Transcripts Sequences ..."
[1] "get data for gene ID ENSMUSG00000005198"
[1] "Get mouse Transcripts Sequences ..."
[1] "get data for gene ID ENSRNOG00000028834"
[1] "Get rat Transcripts Sequences ..."
[1] "get data for gene ID ENSMFAG00000007042"
[1] "Get Macaca_fascicularis Transcripts Sequences ..."
</span><span class="GD15MCFCOTB  ace_constant ace_language" style="color: rgb(255, 98, 140);">Error in data.frame(seqnames = paste0("chr", gene_info$data$seq_region_name),  : 
  arguments imply differing number of rows: 1, 0
</span><span class="GD15MCFCOTB  ace_constant ace_language" style="color: rgb(255, 98, 140);">In addition: </span><span class="GD15MCFCOTB  ace_constant ace_language" style="color: rgb(255, 98, 140);">Warning message:
</span><span class="GD15MCFCOTB  ace_constant ace_language" style="color: rgb(255, 98, 140);">In min(which((gtf.exon$end - data$Translation$end) &gt; 0)) :
</span>

Please fix ...

**Comment by syhwang-snu** [comment]
sure....

**Comment by syhwang-snu** [comment]
solved....
